### PR TITLE
Fix #220 - Update Fares v2 objects to the current spec

### LINKED ISSUE #220: Fares v2 objects are out of date
**Summary:** 

Currently trying to load properly formatted Fares v2 data will result in exceptions being thrown. This is happening because the current implementation was done a year ago, before the Fares v2 spec was finalized, and some key breaking changes have been made.

**Steps to reproduce:** 

Attempt to load the [MBTA GTFS feed](https://www.mbta.com/developers/gtfs).

**Expected behavior:** 

The feed is loaded successfully

**Observed behavior:** 

Exceptions are thrown due to multiple FareProducts with the same ID existing (which is valid according to the spec).
```
19:17:54.436 ERROR [main]  (OTPMain.java:60) An uncaught error occurred inside OTP: io error: entityType=org.onebusaway.gtfs.model.FareProduct path=fare_products.txt lineNumber=3
org.onebusaway.csv_entities.exceptions.CsvEntityIOException: io error: entityType=org.onebusaway.gtfs.model.FareProduct path=fare_products.txt lineNumber=3
        at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:161)
        at org.onebusaway.gtfs.serialization.GtfsReader.readEntities(GtfsReader.java:189)
        at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
        at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
        at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:108)
        at org.opentripplanner.gtfs.graphbuilder.GtfsModule.loadBundle(GtfsModule.java:293)
        at org.opentripplanner.gtfs.graphbuilder.GtfsModule.buildGraph(GtfsModule.java:125)
        at org.opentripplanner.graph_builder.GraphBuilder.run(GraphBuilder.java:175)
        at org.opentripplanner.standalone.OTPMain.startOTPServer(OTPMain.java:141)
        at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:55)
Caused by: org.onebusaway.gtfs.serialization.DuplicateEntityException: duplicate entity id: type=org.onebusaway.gtfs.model.FareProduct id=mbta-ma-us_id=prod_boat_zone_1a|category=null|container=null
        at org.onebusaway.gtfs.serialization.GtfsReader$EntityHandlerImpl.registerAgencyId(GtfsReader.java:397)
        at org.onebusaway.gtfs.serialization.GtfsReader$EntityHandlerImpl.handleEntity(GtfsReader.java:341)
        at org.onebusaway.csv_entities.CsvEntityReader$EntityHandlerImpl.handleEntity(CsvEntityReader.java:225)
        at org.onebusaway.csv_entities.IndividualCsvEntityReader.readEntity(IndividualCsvEntityReader.java:148)
        at org.onebusaway.csv_entities.IndividualCsvEntityReader.handleLine(IndividualCsvEntityReader.java:98)
        at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:157)
        ... 9 common frames omitted
```

**Platform:** 

Mac OS Ventura, Java 17.0.7, onebusaway-gtfs-modules 1.4.3

### PR DESCRIPTION
**Pull request by EmmaSimon**
Some changes to the spec were made since the initial implementation, this brings the Java objects up to date.

**Summary:**

The initial Fares v2 changes (#197, #203) were done about a year ago, and since then, the [Fares v2 spec](https://gtfs.org/schedule/reference/#fare_mediatxt) has been [changed](https://gtfs.org/extensions/fares-v2/) in a few key ways. See #220 for more details.

* Change the name of `FareContainer` to `FareMedium` (and any references in variable and method names)
* Remove the mapping with `FareProductFieldMappingFactory` in `FareLegRule`, now there can be multiple `FareProducts` with the same `fare_product_id`, and mapping to an `ArrayList<FareProduct>` would have required quite a bit of refactoring and additional code
* Remove `fareContainer` and `riderCategory` from `FareLegRule`, these now exist only in the `FareProduct`
* Update `FareLegRule::getId` and `FareProductFieldMappingFactory::fareProductIdPrimaryKey` to reflect the combination of fields that uniquely identify fare legs and fare products
* Update tests to correspond to these changes

**Expected behavior:** 

This should successfully load any current Fares v2 GTFS files. Loading using the outdated spec will fail, but any outdated fields should be corrected, and currently, properly formatted Fares v2 GTFS files are failing to load.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Format the title like "Fix #<issue_number> - short description of fix and changes"
- [x] Linked all relevant issues

### CODE REVIEW

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java [hunk 1]
```diff
@@ -15,35 +15,27 @@
...
 package org.onebusaway.gtfs.model;
 
-import java.util.Optional;
 import org.onebusaway.csv_entities.schema.annotations.CsvField;
 import org.onebusaway.csv_entities.schema.annotations.CsvFields;
+import org.onebusaway.gtfs.serialization.mappings.DefaultAgencyIdFieldMappingFactory;
 import org.onebusaway.gtfs.serialization.mappings.EntityFieldMappingFactory;
-import org.onebusaway.gtfs.serialization.mappings.FareProductFieldMappingFactory;
+
+import javax.swing.text.html.Option;
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:23]:
```suggestion
```
Import not needed.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java [hunk 2]
```diff
@@ -88,40 +86,26 @@ public void setNetworkId(String networkId) {
...
-    String containerId = Optional.ofNullable(fareContainer).map(c -> c.getId().getId()).orElse(null);
-    String categoryId = Optional.ofNullable(riderCategory).map(c -> c.getId().getId()).orElse(null);
+    String fromAreaId = Optional.ofNullable(fromArea).map(Area::getAreaId).orElse(null);
+    String toAreaId = Optional.ofNullable(toArea).map(Area::getAreaId).orElse(null);
+    String baseLegGroupId = Optional.ofNullable(legGroupId).map(AgencyAndId::getId).orElse(null);
+    String baseProductId = Optional.ofNullable(fareProductId).map(AgencyAndId::getId).orElse(null);
     return String.format(
-      "id=%s|network=%s|fromArea=%s|toArea=%s|container=%s|category=%s",
-      fareProduct.getFareProductId().getId(), networkId, fromAreaId, toAreaId, containerId, categoryId
+      "id=%s|product=%s|network=%s|fromArea=%s|toArea=%s",
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:94]:
```suggestion
      "groupId=%s|product=%s|network=%s|fromArea=%s|toArea=%s",
```

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java [hunk 3]
```diff
@@ -124,8 +124,14 @@ public void setCurrency(String currency) {
   @Override
   public AgencyAndId getId() {
     String riderCategoryId = Optional.ofNullable(riderCategory).map(c -> c.getId().getId()).orElse(null);
-    String fareContainerId = Optional.ofNullable(fareContainer).map(c -> c.getId().getId()).orElse(null);
-    return FareProductFieldMappingFactory.fareProductId(fareProductId.getAgencyId(), fareProductId.getId(), riderCategoryId, fareContainerId);
+    String fareMediumId = Optional.ofNullable(fareMedium).map(c -> c.getId().getId()).orElse(null);
+    return FareProductFieldMappingFactory.fareProductId(
+            fareProductId.getAgencyId(),
+            fareProductId.getId(),
+            getName(),
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:131]: Why is the name now part of the ID? Accoring to the spec this isn't part of the primary key.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java [hunk 4]
```diff
@@ -54,28 +46,34 @@ public final class FareLegRule extends IdentityBean<String> {
   @CsvField(name = "distance_type", optional = true)
   private Integer distanceType;
 
-  public String getLegGroupId() {
+  @CsvField(
+    name = "fare_product_id",
+    mapping = DefaultAgencyIdFieldMappingFactory .class
+  )
+  private AgencyAndId fareProductId;
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:53]: I know we talked about this, but please remind me again why you cannot put the `FareProduct` instance there?

In the spec there is still only a single fare product per fare leg rule. A _group_ of rules may have several fare product but not the individual instance.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java [hunk 5]
```diff
@@ -88,40 +86,26 @@ public void setNetworkId(String networkId) {
 
   @Override
   public String getId() {
-    String containerId = Optional.ofNullable(fareContainer).map(c -> c.getId().getId()).orElse(null);
-    String categoryId = Optional.ofNullable(riderCategory).map(c -> c.getId().getId()).orElse(null);
+    String fromAreaId = Optional.ofNullable(fromArea).map(Area::getAreaId).orElse(null);
+    String toAreaId = Optional.ofNullable(toArea).map(Area::getAreaId).orElse(null);
+    String baseLegGroupId = Optional.ofNullable(legGroupId).map(AgencyAndId::getId).orElse(null);
+    String baseProductId = Optional.ofNullable(fareProductId).map(AgencyAndId::getId).orElse(null);
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:92]: What is the use of the "base" prefix?

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java (hunk 3 above)
Comment (EmmaSimon) [reply onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:131]: https://docs.google.com/document/d/19j-f-wZ5C_kYXmkLBye1g42U-kvfSVgYLkkG5oyBauY/edit?pli=1

Good catch, I was basing it off of this doc, but the section that includes name isn't grayed, and there's an unaddressed comment that brings up why including the name is probably a bad idea. Maybe that was what caused them to remove that in the final spec? I'll get rid of it.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java (hunk 4 above)
Comment (EmmaSimon) [reply onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:53]: There is only a single fare_product_id per fare leg rule, but there can be multiple fare products with the same ID, since the PK is (fare_product_id, fare_media_id), and fare_leg_rules.txt does not have a fare_media_id to differentiate between them.

Here's a snippet from the MBTA's fare_products.txt:
```
fare_product_id,fare_product_name,fare_media_id,amount,currency
prod_cr_zone_1,Commuter Rail Zone 1 one-way fare,cash,6.5,USD
prod_cr_zone_1,Commuter Rail Zone 1 one-way fare,credit_debit,6.5,USD
prod_cr_zone_1,Commuter Rail Zone 1 one-way fare,mticket,6.5,USD
```

A fare leg rule with the fare_product_id == "prod_cr_zone_1" would need to match all three of those.

Comment (leonardehrenfried) [reply onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareLegRule.java:53]: I see now. Despite the name a `fare_product_id` no longer identifies a single fare product.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareMedium.java [hunk 6]
```diff
@@ -23,50 +23,22 @@
 /**
  * As of July 2022 this file is not yet part of the main GTFS spec.
  */
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareMedium.java:25]: Update this comment - it's now part of the main spec.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java [hunk 7]
```diff
@@ -54,8 +54,8 @@ public final class FareProduct extends IdentityBean<AgencyAndId> {
   private RiderCategory riderCategory;
 
   // not in the main GTFS spec yet (as of June 2022)
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:56]: Remove comment.

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java [hunk 8]
```diff
@@ -32,30 +32,25 @@ public final class FareProduct extends IdentityBean<AgencyAndId> {
   private AgencyAndId fareProductId;
   @CsvField(optional = true, name = "fare_product_name")
   private String name;
-  @CsvField(optional = true)
+  @CsvField()
   private float amount = MISSING_VALUE;
-  @CsvField(optional = true)
+  @CsvField()
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:37]:
```suggestion
  @CsvField
```

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java [hunk 9]
```diff
@@ -32,30 +32,25 @@ public final class FareProduct extends IdentityBean<AgencyAndId> {
   private AgencyAndId fareProductId;
   @CsvField(optional = true, name = "fare_product_name")
   private String name;
-  @CsvField(optional = true)
+  @CsvField()
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:35]:
```suggestion
  @CsvField
```

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java [hunk 10]
```diff
@@ -65,12 +60,12 @@ public void setFareProductId(AgencyAndId fareProductId) {
     this.fareProductId = fareProductId;
   }
 
-  public FareContainer egetFareContainer() {
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/model/FareProduct.java:68]: :scream: "eget"?

File: onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/mappings/FareProductFieldMappingFactory.java [hunk 11]
```diff
@@ -47,13 +47,13 @@ public FieldMapping createFieldMapping(EntitySchemaFactory schemaFactory,
...
-  public static AgencyAndId fareProductId(String agencyId, String fareProductId, String riderCategoryId, String fareContainerId) {
-    String primaryKey = fareProductIdPrimaryKey(fareProductId, riderCategoryId, fareContainerId);
+  public static AgencyAndId fareProductId(String agencyId, String fareProductId, String riderCategoryId, String fareMediumId) {
+    String primaryKey = fareProductIdPrimaryKey(fareProductId, riderCategoryId, fareMediumId);
     return new AgencyAndId(agencyId, primaryKey);
   }
 
-  static String fareProductIdPrimaryKey(String fareProductId, String riderCategoryId, String fareContainerId) {
-    return String.format("id=%s|category=%s|container=%s", fareProductId, riderCategoryId, fareContainerId);
+  static String fareProductIdPrimaryKey(String fareProductId, String riderCategoryId, String fareMediumId) {
```
Comment (leonardehrenfried) [inline onebusaway-gtfs/src/main/java/org/onebusaway/gtfs/serialization/mappings/FareProductFieldMappingFactory.java:55]: I know I originally wrote this code but can we rename this method to `fareProductPrimaryKey`?

Shame on me...

**Review by leonardehrenfried — CHANGES_REQUESTED** [review]
I have two smaller requests but other than those, this looks good!

**Review by sheldonabrown — APPROVED** [review]

**Comment by sheldonabrown** [comment]
Thanks!
